ControleDeContatos/Models/ContatoModel.cs
using System.ComponentModel.DataAnnotations;

namespace ControleDeContatos.Models
{
    public class ContatoModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o nome do contato")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Digite o e-mail do contato")]
        [EmailAddress(ErrorMessage = "O e-mail informado não é valido!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Digite o celular do contato")]
        [Phone(ErrorMessage = "O celular informado não é valido!")]
        public string Celular { get; set; }
    }
}

ControleDeContatos/Models/ErrorViewModel.cs
namespace ControleDeContatos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControleDeContatos/Models/ProdutoModel.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ControleDeContatos.Models
{
    public class ProdutoModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o nome do produto")]
        public string Nome { get; set; }
        [Required]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal PrecoCompra { get; set; }
        [Required]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal PrecoVenda { get; set; }
        [Required]
        public int Quantidade { get; set; }

        public decimal TotalParaVenda()
        {
            return PrecoVenda * Quantidade;
        }
    }

}

ControleDeContatos/Controllers/ContatoController.cs
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace ControleDeContatos.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;
        public ContatoController(IContatoRepositorio contatoRepositorio)
        {
            _contatoRepositorio = contatoRepositorio;
        }
        public IActionResult Index()
        {
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos();
            return View(contatos);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }
        public IActionResult ApagarConfirmacao(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }
        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _contatoRepositorio.Apagar(id);

                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Contato apagado com sucesso";
                }
                else
                {
                    TempData["MensagemErro"] = $"Não foi possivel apagar o contato";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possivel apagar o contato, tente novamente! {erro.Message}";
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepositorio.Adicionar(contato);
                    TempData["MensagemSucesso"] = "Contato cadastrado com sucesso";
                    return RedirectToAction("Index");
                }
                return View(contato);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possivel efetuar o cadastro do contato, tente novamente! {erro.Message}";
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepositorio.Atualizar(contato);
                    TempData["MensagemSucesso"] = "Contato alterado com sucesso";
                    return RedirectToAction("Index");

                }
                return View("Editar", contato);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possivel alterar o contato, tente novamente! {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

ControleDeContatos/Controllers/HomeController.cs
using ControleDeContatos.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ControleDeContatos.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ControleDeContatos/Controllers/ProdutoController.cs
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace ControleDeContatos.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoRepositorio _produtoRepositorio;
        public ProdutoController(IProdutoRepositorio produtoRepositorio)
        {
            _produtoRepositorio = produtoRepositorio;
        }
        public IActionResult Index()
        {
            List<ProdutoModel> produtos = _produtoRepositorio.BuscarTodos();
            return View(produtos);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            ProdutoModel produto = _produtoRepositorio.ListarPorId(id);
            return View(produto);
        }
        public IActionResult ApagarConfirmacao(int id)
        {
            ProdutoModel produto = _produtoRepositorio.ListarPorId(id);
            return View(produto);
        }
        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _produtoRepositorio.Apagar(id);

                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Produto apagado com sucesso";
                }
                else
                {
                    TempData["MensagemErro"] = $"Não foi possivel apagar o produto";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possivel apagar o produto, tente novamente! {erro.Message}";
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public IActionResult Criar(ProdutoModel produto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _produtoRepositorio.Adicionar(produto);
                    TempData["MensagemSucesso"] = "Produto cadastrado com sucesso";
                    return RedirectToAction("Index");
                }
                return View(produto);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possivel efetuar o cadastro do produto, tente novamente! {erro.Message}";
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public IActionResult Alterar(ProdutoModel produto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _produtoRepositorio.Atualizar(produto);
                    TempData["MensagemSucesso"] = "Produto alterado com sucesso";
                    return RedirectToAction("Index");

                }
                return View("Editar", produto);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possivel alterar o produto, tente novamente! {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

ControleDeContatos/Views/Contato/ApagarConfirmacao.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Confirmação para apagar contato";
}

<div class="text-center">
    <h3>Realmente deseja apagar o contato (@Model.Nome)?</h3>
<a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>
<a class="btn btn-danger" role="button" asp-controller="Contato" asp-action="Index">Cancelar exclusão</a>
</div>

ControleDeContatos/Views/Contato/Criar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Criação de contato";
}
<h1 class="display-4">Cadastrar contato</h1>

<form asp-controller="Contato" asp-action="Criar" method="post">
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do contato">
    @Html.ValidationMessageFor(x => x.Nome)
  </div>
  <div class="form-group">
    <label for="email">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o e-mail do contato">
        @Html.ValidationMessageFor(x => x.Email)
  </div>
  <div class="form-group">
    <label for="celular">Celular</label>
        <input type="text" asp-for="Celular" class="form-control" placeholder="Digite o celular do contato">
        @Html.ValidationMessageFor(x => x.Celular)
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Adicionar</button>
  <a class="btn btn-secondary" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

ControleDeContatos/Views/Contato/Editar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Editar contato";
}
<h1 class="display-4">Editar contato</h1>

<form asp-controller="Contato" asp-action="Alterar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do contato">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o e-mail do contato">
        @Html.ValidationMessageFor(x => x.Email)
    </div>
    <div class="form-group">
        <label for="celular">Celular</label>
        <input type="text" asp-for="Celular" class="form-control" placeholder="Digite o celular do contato">
        @Html.ValidationMessageFor(x => x.Celular)
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

ControleDeContatos/Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Lista de contatos";
}
<h1 class="display-4">Contatos</h1>
<div>
    <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Novo</a>
</div>
<div>

    @if(TempData["MensagemSucesso"] != null)
    {    
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert">X</button>
        @TempData["MensagemSucesso"]
    </div>
    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert">X</button>
            @TempData["MensagemErro"]
        </div>
    }
    <br />

    <table class="table" id="table-contatos">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">E-mail</th>
                <th scope="col">Celular</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (ContatoModel contato in Model)
                {
                    <tr>
                        <td>@contato.Nome</td>
                        <td>@contato.Email</td>
                        <td>@contato.Celular</td>
                        <td>
                            <div class="btn-group" role="group" style="display:flex; justify-content:end;">
                                <a role="button" class="btn btn-primary" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

ControleDeContatos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pagina Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <p>Sistema de controle de Contatos</p>
</div>

ControleDeContatos/Views/Produto/ApagarConfirmacao.cshtml
@model ProdutoModel
@{
    ViewData["Title"] = "Confirmação para apagar produto";
}

<div class="text-center">
    <h3>Realmente deseja apagar o produto (@Model.Nome)?</h3>
<a class="btn btn-primary" role="button" asp-controller="Produto" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>
    <a class="btn btn-danger" role="button" asp-controller="Produto" asp-action="Index">Cancelar exclusão</a>
</div>

ControleDeContatos/Views/Produto/Criar.cshtml
@model ProdutoModel
@{
    ViewData["Title"] = "Criação de produto";
}
<h1 class="display-4">Cadastrar produto</h1>

<form asp-controller="Produto" asp-action="Criar" method="post">
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do produto">
    @Html.ValidationMessageFor(x => x.Nome)
  </div>
  <div class="form-group">
    <label for="precoCompra">Preço de Compra</label>
        <input type="text" asp-for="PrecoCompra" class="form-control" placeholder="Digite o preço de compra">
        @Html.ValidationMessageFor(x => x.PrecoCompra)
  </div>
  <div class="form-group">
        <label for="precoVenda">Preço de Venda</label>
        <input type="text" asp-for="PrecoVenda" class="form-control" placeholder="Digite o preço de venda">
        @Html.ValidationMessageFor(x => x.PrecoVenda)
  </div>
    <div class="form-group">
        <label for="quantidade">Quantidade</label>
        <input type="text" asp-for="Quantidade" class="form-control" placeholder="Digite a quantidade">
        @Html.ValidationMessageFor(x => x.Quantidade)
    </div>
  <br />
  <button type="submit" class="btn btn-primary">Adicionar</button>
  <a class="btn btn-secondary" asp-controller="Produto" asp-action="Index" role="button">Voltar</a>
</form>

ControleDeContatos/Views/Produto/Editar.cshtml
@model ProdutoModel
@{
    ViewData["Title"] = "Editar produto";
}
<h1 class="display-4">Editar produto</h1>

<form asp-controller="Produto" asp-action="Alterar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do produto">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <div class="form-group">
        <label for="precoCompra">Preço de Compra</label>
        <input type="text" asp-for="PrecoCompra" class="form-control" placeholder="Digite o preço de compra">
        @Html.ValidationMessageFor(x => x.PrecoCompra)
    </div>
    <div class="form-group">
        <label for="precoVenda">Preço de Venda</label>
        <input type="text" asp-for="PrecoVenda" class="form-control" placeholder="Digite o preço de venda">
        @Html.ValidationMessageFor(x => x.PrecoVenda)
    </div>
    <div class="form-group">
        <label for="quantidade">Quantidade</label>
        <input type="text" asp-for="Quantidade" class="form-control" placeholder="Digite a quantidade">
        @Html.ValidationMessageFor(x => x.Quantidade)
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Produto" asp-action="Index" role="button">Voltar</a>
</form>

ControleDeContatos/Views/Produto/Index.cshtml
@model List<ProdutoModel>
@{
    ViewData["Title"] = "Lista de produtos";
}
<h1 class="display-4">Produtos</h1>
<div>
    <a class="btn btn-primary" role="button" asp-controller="Produto" asp-action="Criar">Novo</a>
</div>
<div>

    @if(TempData["MensagemSucesso"] != null)
    {    
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert">X</button>
        @TempData["MensagemSucesso"]
    </div>
    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert">X</button>
            @TempData["MensagemErro"]
        </div>
    }
    <br />

    <table class="table" id="table-contatos">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Preço de Compra</th>
                <th scope="col">Preço de Venda</th>
                <th scope="col">Quantidade</th>
                <th scope="col">Total para venda</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (ProdutoModel produto in Model)
                {
                    <tr>
                        <td>@produto.Nome</td>
                        <td>R$ @produto.PrecoCompra</td>
                        <td>R$ @produto.PrecoVenda</td>
                        <td>@produto.Quantidade</td>
                        <td>R$ @produto.TotalParaVenda()</td>
                        
                        <td>
                            <div class="btn-group" role="group" style="display:flex; justify-content:end;">
                                <a role="button" class="btn btn-primary" asp-route-id="@produto.Id" asp-controller="Produto" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@produto.Id" asp-controller="Produto" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

ControleDeContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ControleDeContatos.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de Contatos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Controle de Contatos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>